In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet # Ridge: L2, Lasso: L1, ElasticNet: L1+L2
from sklearn.metrics import mean_squared_error
import numpy as np

In [20]:
data=pd.read_csv("E:\\AI & Machine Learning\\03.Machine Learning\\Practice\\Datasets-CSV\\Boston.csv")

In [21]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [22]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) # 80% train, 20% test

In [24]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [25]:
model.coef_


array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [26]:
rmodel=Ridge(alpha=0.5) # alpha=0.5, 0.1, 0.01, 0.001, 0.0001 ,alpha=lambda 
rmodel.fit(x_train,y_train)
rmodel.coef_

array([-1.23337821e-01,  4.56332581e-02,  6.23799450e-04, -1.12926578e+01,
        3.80885494e+00, -7.00373944e-03, -1.33554482e+00,  2.51700207e-01,
       -1.24976491e-02, -1.02530199e+00,  8.99905773e-03, -4.98012383e-01])

In [27]:
lmodel=Lasso(alpha=1)
lmodel.fit(x_train,y_train)
lmodel.coef_

array([-0.05889028,  0.05317657, -0.        , -0.        ,  0.67954962,
        0.01684077, -0.6487664 ,  0.198738  , -0.01399421, -0.86421958,
        0.00660309, -0.73120957])

In [28]:
emodel=ElasticNet(alpha=1)
emodel.fit(x_train,y_train)
emodel.coef_

array([-0.07922321,  0.05637835, -0.02484651, -0.        ,  0.84270351,
        0.01551814, -0.75788431,  0.22869565, -0.01471232, -0.85689217,
        0.00690502, -0.71471227])

In [29]:
y_pred=model.predict(x_test) 
y_predr=rmodel.predict(x_test)
y_predl=lmodel.predict(x_test)
y_prede=emodel.predict(x_test)

In [31]:
print(np.sqrt(mean_squared_error(y_test,y_pred)))
print(np.sqrt(mean_squared_error(y_test,y_predr)))
print(np.sqrt(mean_squared_error(y_test,y_predl)))
print(np.sqrt(mean_squared_error(y_test,y_prede)))

5.849124083786676
5.8809716057145005
6.457561211475196
6.376937515586475
