In [2]:
import numpy as np

In [7]:
np.random.randint(2,5,10)

array([4, 3, 3, 2, 3, 4, 4, 4, 3, 2])

In [8]:
np.random.randint(2,5,(10,10))

array([[3, 4, 2, 4, 3, 2, 2, 3, 4, 4],
       [2, 2, 2, 2, 2, 4, 2, 4, 2, 2],
       [3, 2, 4, 3, 4, 4, 3, 3, 2, 3],
       [2, 3, 3, 3, 2, 3, 2, 3, 3, 3],
       [2, 2, 3, 2, 2, 4, 3, 2, 2, 2],
       [4, 3, 3, 3, 3, 2, 3, 2, 4, 2],
       [2, 4, 3, 4, 4, 2, 2, 3, 3, 4],
       [4, 3, 4, 4, 4, 4, 3, 3, 2, 2],
       [2, 3, 4, 3, 4, 4, 2, 4, 3, 4],
       [4, 3, 3, 4, 4, 2, 2, 2, 3, 4]])

In [9]:
np.random.uniform(2,5,(10,10))

array([[2.77145595, 2.96269435, 4.39354197, 3.27019329, 4.51148736,
        2.43269253, 3.84141885, 3.34820483, 2.90586639, 4.74772324],
       [3.86482289, 2.04855621, 2.1879335 , 2.08379759, 3.58246556,
        4.52634395, 3.10430089, 2.43886637, 3.39355632, 3.61619461],
       [3.29949589, 2.32523862, 2.73354894, 4.92551467, 4.83442645,
        3.78278714, 2.73022514, 2.10620509, 3.12544343, 4.41669113],
       [3.36210443, 3.41559387, 3.6928869 , 2.81124152, 2.96493471,
        3.87688105, 2.17139982, 2.32580655, 4.5770108 , 2.00122596],
       [3.16435694, 2.30688138, 3.4354365 , 3.25979057, 3.93744896,
        2.64226924, 2.46567256, 2.94689436, 3.09361212, 3.52966384],
       [3.64076195, 3.67802529, 4.75438778, 3.34865093, 2.79150348,
        2.4903935 , 3.96764623, 3.9356414 , 4.52548632, 2.57114305],
       [2.82351091, 4.7582414 , 4.47666352, 2.65446391, 3.00937433,
        2.24549593, 3.89512688, 2.74524168, 3.50368224, 2.69673225],
       [2.69441746, 4.7226536 , 2.3011301

In [13]:
np.random.random(20)

array([0.89732429, 0.19376449, 0.54643211, 0.27884754, 0.53542777,
       0.82123714, 0.76844583, 0.68345636, 0.55590552, 0.46168949,
       0.59690508, 0.39850873, 0.18722883, 0.93889186, 0.77819105,
       0.33201026, 0.06138053, 0.0672897 , 0.3304839 , 0.09846234])

In [14]:
np.random.random(20).reshape(2,10)

array([[0.95715509, 0.11143384, 0.05948171, 0.26583478, 0.56182623,
        0.53137871, 0.76700534, 0.46503747, 0.95389419, 0.51853586],
       [0.33167003, 0.05073305, 0.68675984, 0.52151351, 0.44007038,
        0.44029443, 0.59419332, 0.6751472 , 0.15698199, 0.74622973]])

In [17]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
tuple(range(10))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [20]:
set(range(10))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [22]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [23]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [24]:
a=np.array([1,2,3,4,5,6,6,7,7])

In [25]:
a

array([1, 2, 3, 4, 5, 6, 6, 7, 7])

In [26]:
a[-1]

7

In [27]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 7]])

In [28]:
 a[1:3]

array([2, 3])

In [33]:
Ar1=np.array([1,2,3,4,4,5,5,6,67,7,1,2])

In [34]:
Ar1

array([ 1,  2,  3,  4,  4,  5,  5,  6, 67,  7,  1,  2])

In [36]:
Ar1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 4,  5,  5,  6],
       [67,  7,  1,  2]])

In [37]:
Ar1.shape

(12,)

In [38]:
Ar2=np.array([[1,2,3],[4,5,6]])

In [39]:
Ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
Ar2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [41]:
type(Ar2)

numpy.ndarray

In [42]:
sss=np.array([2,2,2,2,2,2,2,4])

In [43]:
sss

array([2, 2, 2, 2, 2, 2, 2, 4])

In [44]:
m1=np.array([[1,2,3],[2,3,4],[2,3,3]])
m2=np.array([[22,33,44],[3,4,55],[44,55,66]])

In [45]:
m1

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 3]])

In [46]:
m2

array([[22, 33, 44],
       [ 3,  4, 55],
       [44, 55, 66]])

In [47]:
m1+m2

array([[23, 35, 47],
       [ 5,  7, 59],
       [46, 58, 69]])

In [48]:
m1-m2

array([[-21, -31, -41],
       [ -1,  -1, -51],
       [-42, -52, -63]])

In [55]:
m1*m2 # hadamart multiflicaton

array([[ 22,  66, 132],
       [  6,  12, 220],
       [ 88, 165, 198]])

In [56]:
s=100*m2
s

array([[2200, 3300, 4400],
       [ 300,  400, 5500],
       [4400, 5500, 6600]])

In [57]:
m2/100

array([[0.22, 0.33, 0.44],
       [0.03, 0.04, 0.55],
       [0.44, 0.55, 0.66]])

In [58]:
s/100


array([[22., 33., 44.],
       [ 3.,  4., 55.],
       [44., 55., 66.]])

In [62]:
np.dot(m1,m2) #real multiflication

array([[160, 206, 352],
       [229, 298, 517],
       [185, 243, 451]])

In [63]:
m1.dot(m2) #real multiflication

array([[160, 206, 352],
       [229, 298, 517],
       [185, 243, 451]])

In [64]:
m1


array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 3]])

In [67]:
m1+100 # broudcasting, in the matrices is not allow

array([[101, 102, 103],
       [102, 103, 104],
       [102, 103, 103]])

In [68]:
np.trace(m1)

7

In [69]:
np.transpose(m1)

array([[1, 2, 2],
       [2, 3, 3],
       [3, 4, 3]])

In [70]:
np.linalg.det(m1)

1.0

In [72]:
np.linalg.inv(m1)

array([[-3.,  3., -1.],
       [ 2., -3.,  2.],
       [-0.,  1., -1.]])

In [74]:
a,b=np.linalg.eig(m1)

In [75]:
a

array([ 7.90188052, -0.17382122, -0.72805931])

In [76]:
b

array([[-0.45096957, -0.75208699, -0.77373366],
       [-0.66749798,  0.64494428, -0.22166747],
       [-0.59251405, -0.13569097,  0.5934642 ]])

In [77]:
a=np.array([1,2,3,4,5,5,6,7,87,8,98,9,9,9,1])

In [78]:
a

array([ 1,  2,  3,  4,  5,  5,  6,  7, 87,  8, 98,  9,  9,  9,  1])

In [80]:
a>=20

array([False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False])

In [81]:
a[a>=4]

array([ 4,  5,  5,  6,  7, 87,  8, 98,  9,  9,  9])

In [82]:
np.exp(10) #e**10

22026.465794806718

In [101]:
np.e**10

22026.465794806703

In [83]:
np.sin(28)

0.27090578830786904

In [84]:
np.cos(19)

0.9887046181866692

In [85]:
np.tan(10)

0.6483608274590866

In [86]:
np.power(3,2)

9

In [87]:
np.round(12.2222345)

12.0

In [89]:
pi=(27/3)

In [90]:
pi

9.0

In [91]:
np.pi

3.141592653589793

In [94]:
np.pi


3.141592653589793

In [95]:
np.e

2.718281828459045

In [96]:
np.inf

inf

In [97]:
np.NINF

-inf

In [98]:
-np.inf


-inf

In [99]:
np.nan #nothing

nan

In [102]:
z=np.array([22,3,44,45556,6,7,7,87,898,9,2])

In [103]:
z

array([   22,     3,    44, 45556,     6,     7,     7,    87,   898,
           9,     2])

In [104]:
z.min()

2

In [106]:
z.max()

45556

In [107]:
z.mean()

4240.090909090909

In [108]:
z.sum()

46641

In [110]:
np.max(z)

45556

In [111]:
np.min(z)

2

In [113]:
z.sort()

In [122]:
z

array([    2,     3,     6,     7,     7,     9,    22,    44,    87,
         898, 45556])

In [123]:
L=[2,47,8,4,22,2,1]

In [124]:
L.sort(reverse=True)

In [125]:
L

[47, 22, 8, 4, 2, 2, 1]

In [126]:
a=np.array([[1,2,3],[4,5,56]])
b=np.array([[1,2,6],[33,44,55]])

In [127]:
np.hstack((a,b))

array([[ 1,  2,  3,  1,  2,  6],
       [ 4,  5, 56, 33, 44, 55]])

In [130]:
np.vsplit(a,2)

[array([[1, 2, 3]]), array([[ 4,  5, 56]])]

In [132]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5, 56],
       [ 1,  2,  6],
       [33, 44, 55]])

In [136]:
np.vsplit(a,2)

[array([[1, 2, 3]]), array([[ 4,  5, 56]])]

In [137]:
L=[11,22,33,44,55,66,77,888]

In [139]:
map(str,L)

In [140]:
list(map(str,L))

['11', '22', '33', '44', '55', '66', '77', '888']

In [141]:
list(map(float,L))

[11.0, 22.0, 33.0, 44.0, 55.0, 66.0, 77.0, 888.0]

In [142]:
L=[11,22,33,44,55,66,77,888]
arr=np.array(L)

In [143]:
arr

array([ 11,  22,  33,  44,  55,  66,  77, 888])

In [144]:
arr.astype(float)

array([ 11.,  22.,  33.,  44.,  55.,  66.,  77., 888.])