#**Lable Encoding**

In [28]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [29]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [30]:
data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AI & Machine Learning/Machine Learning/ML Practice/13.Dummy_Variables/GPA_data.CSV")

In [31]:
data.head(10)

ID  Gender  Age Extra_Curricular  Study_Hours  Annual_Income  \
0  8867    Male   22        Societies           10        1318792   
1  1316  Female   24        Societies            9         874657   
2  9443    Male   22        Societies           15        1098331   
3  1829  Female   25               No            9        1680585   
4  1989    Male   26               No            7        1361560   
5  7297  Female   25        Societies            5         887824   
6  7447    Male   23        Societies           10        1957325   
7  2018    Male   21        Societies            7        1602856   
8  1136  Female   23        Societies            8         429437   
9  7702    Male   26           Sports            6         536744   

   Distance_From_Home   GPA  
0                 154  1.76  
1                 181  3.88  
2                  94  1.73  
3                   8  1.29  
4                 122  3.19  
5                 107  2.42  
6                  22  3.05  
7                 130  2.14  
8                 124  2.07  
9                  81  1.85

In [32]:
le=LabelEncoder()

In [33]:
le.fit_transform(data["Gender"])

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,

In [34]:
le.fit_transform(data["Extra_Curricular"])

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1,
       0, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1,
       0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 1, 0, 0, 0, 0, 2, 2, 1, 0, 2, 0,
       1, 1, 1, 1, 0, 2, 2, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 2, 1, 0, 0, 2,
       2, 0, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 2, 1, 1, 1, 1, 1, 0, 1, 2, 2,
       2, 0, 0, 1, 0, 1, 2, 2, 1, 0, 0, 2, 1, 1, 0, 2, 2, 2, 2, 0, 0, 0,
       0, 1, 1, 1, 2, 2, 1, 1, 1, 0, 2, 1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2,
       0, 1, 0, 2, 2, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1, 1, 2,
       1, 1, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 0,
       0, 0, 1, 2, 0, 2, 0, 2, 1, 2, 0, 2, 2, 1, 2, 0, 1, 0, 2, 0, 0, 1,
       0, 1, 1, 0, 2, 0, 1, 1, 2, 1, 2, 0, 1, 0, 2, 1, 2, 1, 1, 2, 1, 2,
       0, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 1, 0, 2, 2, 1, 2, 0, 2, 1, 1, 1,
       1, 0, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 2, 1,
       2, 2, 2, 1, 1, 0, 0, 0, 0, 2, 0, 2, 1, 1, 2,

In [35]:
data["Extra_Curricular"].unique()

array(['Societies', 'No', 'Sports'], dtype=object)

In [36]:
data["Extra_Curricular"]=le.fit_transform(data["Extra_Curricular"])
data["Gender"]=le.fit_transform(data["Gender"])

In [37]:
data

ID  Gender  Age  Extra_Curricular  Study_Hours  Annual_Income  \
0    8867       1   22                 1           10        1318792   
1    1316       0   24                 1            9         874657   
2    9443       1   22                 1           15        1098331   
3    1829       0   25                 0            9        1680585   
4    1989       1   26                 0            7        1361560   
..    ...     ...  ...               ...          ...            ...   
995  5129       0   22                 0            5        1675219   
996  2365       1   24                 0            8         947439   
997  5140       1   26                 2            6        1912975   
998  4976       1   22                 1           12         341543   
999  6398       1   23                 0           12         975142   

     Distance_From_Home   GPA  
0                   154  1.76  
1                   181  3.88  
2                    94  1.73  
3                     8  1.29  
4                   122  3.19  
..                  ...   ...  
995                  27  2.32  
996                 125  2.70  
997                  67  1.36  
998                  86  1.88  
999                  87  3.36  

[1000 rows x 8 columns]

********************************

In [38]:
data[["Extra_Curricular","Gender"]]=data[["Extra_Curricular","Gender"]].apply(lambda col:le.fit_transform(col))

In [39]:
data.head()

ID  Gender  Age  Extra_Curricular  Study_Hours  Annual_Income  \
0  8867       1   22                 1           10        1318792   
1  1316       0   24                 1            9         874657   
2  9443       1   22                 1           15        1098331   
3  1829       0   25                 0            9        1680585   
4  1989       1   26                 0            7        1361560   

   Distance_From_Home   GPA  
0                 154  1.76  
1                 181  3.88  
2                  94  1.73  
3                   8  1.29  
4                 122  3.19

# **One Hot Encoding**

In [40]:
ohe= OneHotEncoder()

In [41]:
data["Extra_Curricular"].values.reshape(len(data["Extra_Curricular"].values),1)

array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [0],
       [2],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [0],
       [0],
       [0],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [1],
       [0],
       [2],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [0],
       [0],
    

In [42]:
ohot_encoded=ohe.fit_transform(data["Extra_Curricular"].values.reshape(len(data["Extra_Curricular"].values),1)).toarray()

In [43]:
ohot_encoded[:20,:]

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [44]:
data["Extra_Curricular"][:20]

0     1
1     1
2     1
3     0
4     0
5     1
6     1
7     1
8     1
9     2
10    1
11    2
12    2
13    2
14    2
15    0
16    0
17    2
18    0
19    0
Name: Extra_Curricular, dtype: int64

In [45]:
ohot_encoded2=ohot_encoded2=ohot_encoded[:,1:].astype(int)

In [46]:
df_ohot=pd.DataFrame(ohot_encoded2,columns=["Societies","Sports"])

In [47]:
pd.concat([data,df_ohot],axis=1)

ID  Gender  Age  Extra_Curricular  Study_Hours  Annual_Income  \
0    8867       1   22                 1           10        1318792   
1    1316       0   24                 1            9         874657   
2    9443       1   22                 1           15        1098331   
3    1829       0   25                 0            9        1680585   
4    1989       1   26                 0            7        1361560   
..    ...     ...  ...               ...          ...            ...   
995  5129       0   22                 0            5        1675219   
996  2365       1   24                 0            8         947439   
997  5140       1   26                 2            6        1912975   
998  4976       1   22                 1           12         341543   
999  6398       1   23                 0           12         975142   

     Distance_From_Home   GPA  Societies  Sports  
0                   154  1.76          1       0  
1                   181  3.88          1       0  
2                    94  1.73          1       0  
3                     8  1.29          0       0  
4                   122  3.19          0       0  
..                  ...   ...        ...     ...  
995                  27  2.32          0       0  
996                 125  2.70          0       0  
997                  67  1.36          0       1  
998                  86  1.88          1       0  
999                  87  3.36          0       0  

[1000 rows x 10 columns]

In [48]:
data.drop("Extra_Curricular",axis=1,inplace=True)

In [49]:
data.head()

ID  Gender  Age  Study_Hours  Annual_Income  Distance_From_Home   GPA
0  8867       1   22           10        1318792                 154  1.76
1  1316       0   24            9         874657                 181  3.88
2  9443       1   22           15        1098331                  94  1.73
3  1829       0   25            9        1680585                   8  1.29
4  1989       1   26            7        1361560                 122  3.19