In [69]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

In [70]:
data=pd.read_csv("E:\\AI & Machine Learning\\03.Machine Learning\\Practice\\Datasets-CSV\\Boston.csv")

In [71]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [72]:
df_x=data.iloc[:,:12]
df_y=data.iloc[:,12]

In [73]:
df_x

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0    0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1    0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2    0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3    0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4    0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   
..       ...   ...    ...    ...    ...   ...     ...  ...  ...      ...   
501  0.06263   0.0  11.93  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527   0.0  11.93  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076   0.0  11.93  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959   0.0  11.93  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741   0.0  11.93  0.573  6.030  80.8  2.5050    1  273     21.0   

      black  lstat  
0    396.90   4.98  
1    396.90   9.14  
2    392.83   4.03  
3    394.63   2.94  
4    396.90   5.33  
..      ...    ...  
501  391.99   9.67  
502  396.90   9.08  
503  396.90   5.64  
504  393.45   6.48  
505  396.90   7.88  

[506 rows x 12 columns]

In [74]:
df_y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [75]:
rfe=  RFE(estimator=LinearRegression(),n_features_to_select=5) # n_features_to_select=5 means we want to select 5 features

In [76]:
elm_fit=rfe.fit(df_x,df_y)

In [77]:
elm_fit

RFE(estimator=LinearRegression(), n_features_to_select=5)

In [78]:
df_x.shape

(506, 12)

In [79]:
df_x.columns # it will give error because df_x is not a dataframe it is a numpy array

Index(['crim', 'zn', 'indus', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat'],
      dtype='object')

In [80]:
elm_fit.support_

array([False, False, False,  True,  True, False,  True, False, False,
        True, False,  True])

In [88]:
elm_fit.ranking_

array([3, 5, 4, 1, 1, 8, 1, 2, 6, 1, 7, 1])

In [81]:
selected_features=df_x.columns[elm_fit.support_]

In [82]:
df_x[selected_features]

nox     rm     dis  ptratio  lstat
0    0.538  6.575  4.0900     15.3   4.98
1    0.469  6.421  4.9671     17.8   9.14
2    0.469  7.185  4.9671     17.8   4.03
3    0.458  6.998  6.0622     18.7   2.94
4    0.458  7.147  6.0622     18.7   5.33
..     ...    ...     ...      ...    ...
501  0.573  6.593  2.4786     21.0   9.67
502  0.573  6.120  2.2875     21.0   9.08
503  0.573  6.976  2.1675     21.0   5.64
504  0.573  6.794  2.3889     21.0   6.48
505  0.573  6.030  2.5050     21.0   7.88

[506 rows x 5 columns]

In [83]:
x=df_x[selected_features].values
y=df_y.values   

In [84]:
x

array([[ 0.538 ,  6.575 ,  4.09  , 15.3   ,  4.98  ],
       [ 0.469 ,  6.421 ,  4.9671, 17.8   ,  9.14  ],
       [ 0.469 ,  7.185 ,  4.9671, 17.8   ,  4.03  ],
       ...,
       [ 0.573 ,  6.976 ,  2.1675, 21.    ,  5.64  ],
       [ 0.573 ,  6.794 ,  2.3889, 21.    ,  6.48  ],
       [ 0.573 ,  6.03  ,  2.505 , 21.    ,  7.88  ]])

In [85]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [86]:
x_sel=rfe.fit_transform(df_x,df_y) # it will give same result as above

In [87]:
x_sel

array([[ 0.538 ,  6.575 ,  4.09  , 15.3   ,  4.98  ],
       [ 0.469 ,  6.421 ,  4.9671, 17.8   ,  9.14  ],
       [ 0.469 ,  7.185 ,  4.9671, 17.8   ,  4.03  ],
       ...,
       [ 0.573 ,  6.976 ,  2.1675, 21.    ,  5.64  ],
       [ 0.573 ,  6.794 ,  2.3889, 21.    ,  6.48  ],
       [ 0.573 ,  6.03  ,  2.505 , 21.    ,  7.88  ]])