**Cross Validation**

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold,cross_val_score # K-fold cross validation
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, SCORERS


In [28]:
data=pd.read_csv("E:\\AI & Machine Learning\\03.Machine Learning\\Practice\\Datasets-CSV\\Boston.csv")

In [29]:
data.head(10)

crim    zn  indus    nox     rm    age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575   65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421   78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185   61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998   45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147   54.2  6.0622    3  222     18.7   
5  0.02985   0.0   2.18  0.458  6.430   58.7  6.0622    3  222     18.7   
6  0.08829  12.5   7.87  0.524  6.012   66.6  5.5605    5  311     15.2   
7  0.14455  12.5   7.87  0.524  6.172   96.1  5.9505    5  311     15.2   
8  0.21124  12.5   7.87  0.524  5.631  100.0  6.0821    5  311     15.2   
9  0.17004  12.5   7.87  0.524  6.004   85.9  6.5921    5  311     15.2   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  
5  394.12   5.21  28.7  
6  395.60  12.43  22.9  
7  396.90  19.15  27.1  
8  386.63  29.93  16.5  
9  386.71  17.10  18.9

In [30]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

In [31]:
kf=KFold(n_splits=5) # 5-fold cross validation

In [32]:
model=LinearRegression() # Linear Regression model,

In [33]:
list(kf.split(data)) #output = [(train_index, test_index), (train_index, test_index), (train_index, test_index), (train_index, test_index), (train_index, test_index)]

[(array([102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
         115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
         128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
         141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
         167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
         180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
         193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
         206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
         219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
         232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
         245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
         258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
         271, 272, 273, 274, 275, 276,

In [34]:
RMSE=[]

for i in list(kf.split(data)): # i = (train_index, test_index)
    model.fit(x[i[0]],y[i[0]]) # train model
    y_pred=model.predict(x[i[1],:]) # test model
    RMSE.append(np.sqrt(mean_squared_error(y_pred,y[i[1]]))) # calculate RMSE
    

In [35]:
RMSE # RMSE for each fold

[3.5597962719154097,
 4.927922755053193,
 5.276246377079204,
 9.06007444689125,
 6.04196777084675]

In [36]:
np.mean(RMSE) # average RMSE

5.773201524357161

onother methord

In [37]:
cross_val_score(model,x,y,cv=10,scoring="neg_mean_squared_error") # 10-fold cross validation


array([  -9.17006701,  -14.76188969,  -11.78968809,  -34.93168849,
        -26.8851826 ,  -19.52818886,  -10.70555866, -171.48795123,
        -35.0922184 ,  -11.64765827])

In [38]:
cvals=-cross_val_score(model,x,y,cv=10,scoring="neg_mean_squared_error") # RMSE for each fold

In [39]:
cvals

array([  9.17006701,  14.76188969,  11.78968809,  34.93168849,
        26.8851826 ,  19.52818886,  10.70555866, 171.48795123,
        35.0922184 ,  11.64765827])

In [40]:
np.sqrt(cvals) # RMSE for each fold

array([ 3.02821185,  3.84212047,  3.43361152,  5.91030359,  5.18509234,
        4.41907104,  3.271935  , 13.09534082,  5.92386853,  3.41286658])

In [43]:
SCORERS.keys() # list of all scoring methods

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig